Fix built errors of Zhaoxin DMA patches for i386
After merging d3eb024789cc ("Add kh40000_direct_dma_ops for KH-40000
platform"), builting with i386_defconfig, built errors occurred due to
differences in configuration items:
ld:arch/x86/kernel/early-quirks.o: in function `quirk_zhaoxin_dma_patch':
early-quirks.c:(.text+0x2b): undefined reference to kh40000_dma_direct_ops

Therefore, modified the conditionanl items related to the code and
encapsulated the sturct pointer assignment into function.

Fixes: d3eb024789cc ("Add kh40000_direct_dma_ops for KH-40000 platform")

Signed-off-by: leoliu-oc <leoliu-oc@zhaoxin.com>
Signed-off-by: WangYuli <wangyuli@uniontech.com>